### PR TITLE
Core Libraries Committee Report Proposal

### PR DESCRIPTION
**Pull request by andrewthad**
Something I've been thinking about for a while. I would appreciate any feedback. [Rendered Link](https://github.com/andrewthad/ecosystem-proposals/blob/3a1c3efe902e6817960873a1d7b525d506e74734/proposals/0000-core-libraries-committee-report.rst).

### CODE REVIEW

**Comment by ekmett-da** [comment]
There appears to be a bit of a misunderstanding of the structure of the committee encoded in the structure of this proposal.

As it stands, for the most part proposals that are offered for core libraries are acted on by individual members and a lot of this information isn't tallied in one place. We tried working in a centralized fashion with several voices weighing in on each decision at first. Nothing got done. As a result, one of the early actions of the committee was for @snoyberg to update the [Library_submissions](https://wiki.haskell.org/Library_submissions) guidelines to structure things around the existing maintainer-centric workflow. This enabled us to largely get out of each other's way. 

For instance, @dolio handles `vector`, `array` and `primitive` issues, and deals with those issues on their respective issue trackers.

Worse for your proposal, about half of the ["core libraries"](https://wiki.haskell.org/Library_submissions#The_Libraries
) are maintained by folks who are not members of the core libraries committee per se, some of whom may have to take action once every year or two.

https://wiki.haskell.org/Library_submissions#The_Libraries

Consider the `ordNub` example mentioned in the proposal: That proposal is purely in the purview of 
 the maintainers of `containers`, David Feuer. He can do anything he wants with it and _isn't on the committee_. Similarly, Dominic and Carter's work on `random` is off in its own little silo. There is an entire "Windows Task Force" maintaining `Win32`. This list goes on. Each core library is in the hands of its own maintainer and only about half of those maintainers are committee members, and where they are it is largely a coincidental alignment of goals.

I confess, to address the bulk of your concern, I'd be far more inclined to just move `base` proposals, which fall under my purview, to github than to have us all have to become human JIRA report generators.

**Comment by Profpatsch** [comment]
> Consider the ordNub example mentioned in the proposal: That proposal is purely in the purview of
> the maintainers of containers, David Feuer. He can do anything he wants with it and isn't on the committee […contd.]

That’s how it should be, right? A set of trusted individuals, acting in parallel over a large surface area of library code.

**Comment by gbaz** [comment]
An even simpler approach that could address some of the concern is just formalizing: When the core library committee starts considering something specifically, an announcement is posted to libraries@ with a standardized subject line (something like "CLC Consideration Announcement:") and when the CLC reaches a decision on something specifically, an announcement is posted to libraries@ with a standardized subject line (something like "CLC Decision Announcement:"). That way it is easy to traverse the archive to assemble the list of such discussions and decisions, and it is made clear on which occasions the CLC is explicitly involving itself in libraries@ discussions in an oversight role.

**Comment by ekmett-da** [comment]
The only real discussions that have involved the whole CLC in the last year or so have centered around the proposals for adding `liftA2` to `Applicative`, `(<&>)` to `Data.Functor` and some niggling details about how to proceed with the Semigroup-Monoid Proposal.

> When the core library committee starts considering something specifically, an announcement is posted to libraries@ with a standardized subject line (something like "CLC Consideration Announcement:")

I'm not sure that increasing the pomposity of the process is the solution here. =) Are you suggesting that we raise the barrier higher to even talk to each other? It seems like this would be a rather big impediment to starting the very discussions we'd prefer to foster. "The chief cause of problems is solutions."

I very much do think we should work on ensuring that at the end of each proposal on the libraries mailing list that there is a clear decision made and that that decision is stated to the thread, rather than left to trail off. We could stand to do better on this front.

**Comment by andrewthad** [comment]
@ekmett-da @ekmett Thanks for clearing up the process. I'm going to close this proposal in a few days since its assumptions are incorrect. For what it's worth, I do wish that proposals for `base` were tracked somewhere else. On hackage, `base` claims that issues are tracked on the GHC Trac, but there have only [ever been 7 issues](https://ghc.haskell.org/trac/ghc/query?status=closed&status=infoneeded&status=merge&status=new&status=patch&status=upstream&keywords=~base&order=priority) with the `base` keyword there (out of 14000 total issues), so it's difficult for people to discover proposals for `base` and weigh in on the conversation there. I feel like most of them happen on the libraries mailing list, but it's hard to figure out what the resolution of anything is. For example, from the [March 2017 archive](https://mail.haskell.org/pipermail/libraries/2017-March/thread.html), there's a giant thread on deprecating the `Foldable` instance for `Either`, and there's a giant thread on adding a `Foldable` instance for the 3-tuple. I'm not sure what was decided in either of these cases. Maybe no one opened an issue on trac. Maybe someone did and forgot to tag it with the keyword `base`. Maybe you made an executive decision on this, but it's buried 40 comments deep. Next year, someone may bring this up again, and the same arguments might play themselves out. You're spot on when you describe this as "the bulk of my concern", so anything that can be done to improve the discoverability of proposals for `base`, I'm all in favor of.

**Comment by gbaz** [comment]
> Are you suggesting that we raise the barrier higher to even talk to each other? It seems like this would be a rather big impediment to starting the very discussions we'd prefer to foster. "The chief cause of problems is solutions."

What I'm trying to address in the following: There is a lot of discussion on the libraries@ list that the CLC doesn't play a role in _as such_. Now if I want to go and see what discussions it did, there's no easy way except reading through all the archives. If there were some standardized messages sent to indicate certain specific actions, then, by looking through _just the subjects_ of the archives, I could figure that out. For example, even if a message in a thread says explicitly "the CLC decided that xyz" -- how do I find that later? Do I just need to read all the messages until I find one that says that?

**Comment by ekmett** [comment]
@andrewthad: We also have an open slot remaining on the committee, if you feel strongly enough to help out. =)

https://wiki.haskell.org/Core_Libraries_Committee

**Comment by ekmett** [comment]
@gbaz: Most of the time it isn't that the CLC decided anything, but that an individual maintainer that happens to be maintaining a core library did. 

We pushed for a very decentralized process, which managed to help our throughput a great deal, but I do agree that it makes finding all of this information in a centralized manner rather difficult.

**Comment by gbaz** [comment]
@ekmett right. my proposal isn't intended to cover the vast majority of cases where the CLC doesn't decide things directly. For example my recent `ordNub` proposal would not be covered. I'm only suggesting that there be a bit extra formal done in the very exceptional circumstance where the CLC  is called on to act more explicitly and decisively :-)

**Comment by ekmett** [comment]
Anyways, I do rather like the idea of moving `base` proposals out of the GHC trac as it is almost unsearchable. One concern is that many of the `base` proposals are intimately tied to GHC releases, so there has been some pushback on doing so in the past.

**Comment by gbaz** [comment]
A compromise could be the following: _proposals_ for `base` are tracked elsewhere, but _implementation_ of proposals is tracked on the GHC trac. I.e. once something is accepted, then it moves to the GHC trac to keep track of its execution. This, I think, was one iteration of the libraries process some time ago (but the "elsewhere" there was not another bug tracker, but just the libraries@ discussion to begin with).

**Comment by ekmett** [comment]
Yeah, the original intent of the status quo was to have the libraries@ mailing list be that "somewhere else" but I agree that upgrading from that to something like the `base` github tracker to improve visibility seems advisable. One downside is that moving from libraries@ to that tracker becomes yet another place where the ball can be dropped.

**Comment by gbaz** [comment]
imho, the process can sort of be like for what david did with `ordNub` -- i raised the issue on the tracker, but he redirected me to send a message to the list, and once that happened, then the issue was resolved appropriately. so maybe the tracker could be used as an _actual tracker_ and not a discussion venue (weird! i know, right).

**Comment by andrewthad** [comment]
@ekmett I might be interested in applying for the open slot. Is there any way the I can see a list of proposals that have been brought to the committee in the last three years? It looks like there is a `core-libraries-committee` mailing list, but I cannot find an archive of it. It would be nice to get a better picture of what the role entails.

**Comment by ekmett** [comment]
https://groups.google.com/forum/#!forum/haskell-core-libraries

**Pull request closed without merging**
